Attribute VB_Name = "Module2"
'--------------------------------------------
'       SCRIPT INFORMATION
'--------------------------------------------

' Script Name:     Multiple Year Stock Data Analysis
' Author:          J. Enrique Hernandez
' Purpose:         Educational homework for Challenge 2
' Course:          University of Toronto Data Visualization Bootcamp
' Data Source:     Generated by edX Boot Camps LLC
'                  (Intended for educational purposes only)
' Date:            08/30/2023

'--------------------------------------------
'       END OF SCRIPT INFORMATION
'--------------------------------------------

Sub Multiple_Years_Clear_All()

Dim Summary_Table_Row As Integer

 For Each ws In Worksheets

  lastRow = ws.Cells(Rows.Count, 9).End(xlUp).Row

    For i = 2 To lastRow
        ws.Cells(i, 9).Value = " "
        ws.Cells(i, 10).Value = " "
        ws.Cells(i, 10).Interior.Color = xlNone
        ws.Cells(i, 11).Value = " "
        ws.Cells(i, 12).Value = " "
        ws.Cells(i, 15).Value = " "
        ws.Cells(i, 16).Value = " "
    Next i
 Next ws
End Sub
